export default [
  'JSX核心语法',
  'React脚手架',
  'React组件化开发',
  'React中的CSS',
  'AntDesgin组件库',
  'React中axios',
  'React的过渡动画',
  'Redux',
  'React-router',
  'ReactHook',
  'React与TypeScript',
  'React的SSR',
  'React好用的库',
]
